### PR TITLE
fixed spelling error in predict genes

### PR DESCRIPTION
**Pull request by SilasK**

### CODE REVIEW

**Comment by jmtsuji** [comment]
@SilasK Indeed, this fixes an error in ATLAS 2.1.6

**Comment by jmtsuji** [comment]
@SilasK FYI, I noticed that this rule can be a bit of a bottleneck with high numbers of MAGs because it predicts genes for one MAG at a time. I modified the code to predicts genes for multiple MAGs in parallel. It's a bit rough (e.g., how logging works) -- my first time trying this -- but could allow this section of the code to run faster. Guided by [this tutorial](https://stackoverflow.com/a/28463266).

```python
#!/usr/bin/env python3

# python 3.5 without f strings

import argparse
import os
import itertools
from glob import glob
from snakemake.shell import shell
from snakemake.io import glob_wildcards
from multiprocessing.dummy import Pool

def predict_genes(genome,fasta,out_dir,log):

    fna = "{}/{}.fna".format(out_dir,genome)
    faa = "{}/{}.faa".format(out_dir,genome)
    gff = "{}/{}.gff".format(out_dir,genome)

    shell("prodigal -i {fasta} -o {gff} -d {fna} -a {faa} -p meta -f gff 2>> {log} ".format(
        fasta=fasta, log=log,gff=gff,fna=fna,faa=faa)
          )

def predict_genes_genomes(input_dir,out_dir,log,threads):
    genomes_fastas = glob(os.path.join(input_dir,"*.fasta"))

    os.makedirs(out_dir,exist_ok=True)

    pool = Pool(threads)

    genome_names = []
    log_names = []
    for fasta in genomes_fastas:
        genome_name = os.path.splitext(os.path.split(fasta)[-1])[0]
        genome_names.append(genome_name)
        log_names.append(log + '.tmp.' + genome_name)

    pool.starmap(predict_genes, zip(genome_names,genomes_fastas,
                                    itertools.repeat(out_dir),log_names))

    shell("cat {log_names} > {log}".format(log_names=' '.join(log_names), log=log))
    shell("rm {log_names}".format(log_names=' '.join(log_names)))

if __name__ == "__main__":
    try:

        predict_genes_genomes(
            snakemake.input.dir,
            snakemake.output[0],
            snakemake.log[0],
            int(snakemake.threads)
        )

    except NameError:
        p = argparse.ArgumentParser()
        p.add_argument("--input-dir", required = True)
        p.add_argument("--out-dir", required = True)
        p.add_argument("--log", required = True)
        p.add_argument("--threads", required = False, default = 1, type = int)
        args = vars(p.parse_args())
        predict_genes_genomes(**args)

```

Requires threads to be set in rule `predict_genes_genomes` in `genomes.smk`:
```
rule predict_genes_genomes:
    input:
        dir=genome_dir
    output:
        directory("genomes/annotations/genes")
    conda:
        "%s/required_packages.yaml" % CONDAENV
    log:
        "logs/genomes/prodigal.log"
    shadow:
        "shallow"
    threads:
        config.get("threads", 1)
    script:
        "predict_genes_of_genomes.py"
```

Feel free to take or leave this as helpful, but I thought it might be relevant here.

**Comment by SilasK** [comment]
@jmtsuji Good solution, next time you can directly make a Pull Request. You know how to do it?

**Comment by jmtsuji** [comment]
@SilasK Sure, I can make a PR next time -- I've done this before. Thanks for starting a new PR.

**Pull request closed without merging**
