### PR TITLE
Vamb

### PR DESCRIPTION
**Pull request by SilasK**
Adds vamb binner

### CODE REVIEW

**Comment by yanhui09** [comment]
@SilasK 
I fixed some simple bugs (conflicts caused by ambiguous wildcards) in the vamb branch.  
It runs successfull except #https://github.com/RasmussenLab/vamb/issues/59#issuecomment-777572691, which may be caused by the small test data (the one in the tutorial).  Vamb usually works better with more data.
I have made a pr and see if helps.

I didn't check the semibin part, as I probably will not include the semi-supervised strategy into the project in hand for now.
Next I need combine the binners output (metabat, maxbin, concoct, vamb) with dashtool. I will write/re-use some atlas rules. I probably will leave the changes under the vamb branch, since vamb may not suitable for all datasets. If you want to keep the branch clean, I can start a new one.

**Comment by SilasK** [comment]
Thank you @yanhui09 
I try to finish the Vamb in the coming weeks. I also added SemiBin. 

I think I didn't add you to the #417

**Comment by SilasK** [comment]
@yanhui09 Sorry bd769e9 will change the folder names for everything. I tell you when it works for me.

**Comment by yanhui09** [comment]
@SilasK It doesn't matter. My new PR shall have merged your previouse commits.

I also have tried to debug the `semibin` part. As `semibin` is not stable right now and I don't have time to fully fix it, I didn't give a PR for that part. I leave my report here:
1. `semibin` v0.3 has an obvious bug for `.gz` file used in `SemiBin train`. This part has been removed in #https://github.com/BigDataBiology/SemiBin/commit/ea040d4bd27925fd88738207d700cb22baec6e42#diff-80d9229f949ec2902de7f43d3801ecfe799b25a20691bdd0c10eb96694fcaf13 .  But v3.0 still kept this, where in line `871` and `874` (`SemiBin/main.py`) the list varibale `args.contig_fasta` shall be replaced with the item `contig` in the loop.
2. `-r` in `SemiBin predict_taxonomy` is a prefix for the MMseq db, rather than the path. You shall append `/GDTB` at #https://github.com/metagenome-atlas/atlas/blob/21cbebccbfa52c7742210533bbcdb6fa43e8f3be/atlas/rules/semibin.smk#L50
3. simple things: `log` was not placed correctly for `semibin`, you need an extra `s` as `logs`.

Still afther this, I couldn't let `semibin` run. I have some other work, so I gave it up here. 😿

**Comment by SilasK** [comment]
I get it to work

**Pull request merged**
