### PR TITLE
Normalize again

### LINKED ISSUE #288: Rule normalize_reads_before_assembly is not available anymore
Hi @SilasK 

First, thank you so much for this fantastic pipeline. It is easy to use and very straightforward. 
I was wondering if you could add the rule "normalize_reads_before_assembly" again to the pipeline?  I noticed it improves the assembly if I normalize the depth of my MDA-amplified metagenomes in ATLAS 2.0.6. However, I would like to use the new features in ATLAS 2.2, such as the annotation and identification with GTDB. 
Again, thank you very much and stay healthy. 

Melo

### PR DESCRIPTION
**Pull request by SilasK**
Fixes #288

### CODE REVIEW

**Comment by SilasK** [comment]
@MeloOspino  Thank you for your compliment. 

Are you sure that normalization improves assembly? I had the opposite experience at least with metaspades. Could you send me some assembly stats?

In this #289 I tentatively added the normalization again

Do you know how to clone the github repo
change to the branch `normalizeagain`
and install atlas from there?

You need also to  add the line 
` normalize_reads_before_assembly: true` to your config file.

**Comment by MeloOspino** [comment]
Hi @SilasK 
Sorry I did not explain my case well before. My metagenome data came from MDA - amplified samples. When I tried to run them with Meta spades using Atlas 2.2, the assembly crash always due to a lack of memory. Thus I assembled them using megahit, but the assembly ends up being very fragmented. My metagenome data have highly uneven coverage (due to the MDA amplification), and maybe it was the reason for the spades consumption of RAM. I end up finding BBnorm as an alternative to reduce the coverage of high-depth reads but still keeps the dataset intact. I run one of the samples in Atlas 2.0.6 with `normalize_reads_before_assembly: true` with a `target depth of 500x` and `40x`. Spades were able to finish the assembly without compromise the memory, and it was a little less fragmented.
Please find below the assembly stats for the test I made.
  

```
> Stats_sample       Total_Reads Assembled_Reads Percent_Assembled_Reads n_contigs contig_bp   L50   N50   max N_Predicted_Genes
>   <chr>                    <dbl>           <dbl>                   <dbl>     <dbl>     <dbl> <dbl> <dbl> <dbl>             <dbl>
> 1 MC-1_atlas206.40x      9180921        4984917                     54.3     15985  28364438  3115  1663 93153             37600
> 2 MC-1_atlas206.500x     9180921        4678296.                    51.0     18402  28242495  2397  2571 95064             39249
> 3 MC-1_atlas22           9180921        3547646                     38.7     42813  36194110   996 10820  9725             63880
```

**Comment by SilasK** [comment]
Ok, so metaspades is better than megahit. And the normalization would allow for metaspades to pass with limited memory. In my experience spades without normalization worked even better. 

How much memory do you have maximum? 

By the way, the checks don't pass because I cannot install the dependencies needed for atlas. due to restricted resources on the circle ci machines. 
Feel free to start testing the branch.

**Comment by MeloOspino** [comment]
Yes, I will, thank you.
My memory is 250 Gb.

**Comment by SilasK** [comment]
For me most samples pass with 250gb in metaspades.
I just wanted to make sure that you don’t run multiple jobs on the same time each using a fraction of the memory.
But if spades doesn’t work with 250g, you may have large and diverse samples.

**Comment by MeloOspino** [comment]
That could have happened also. However, in some instances, I set the Large mem to 220 or 250, and thread =40 and ran with the same problems.

**Comment by SilasK** [comment]
If you are running atlas on a single node you can append “—resources mem=<large_mem>” to the atlas run command this ensures that only one assembly is run at the same time.

**Comment by MeloOspino** [comment]
I tried that also with `resources mem set to 120` because I was afraid to crash the server (that happened too while running ATLAS with my samples at some point). However, I think I have not tried to run ATLAS 2.2 with all the above options increasing the `resources mem to 220`.    It will worth trying.

**Comment by SilasK** [comment]
@slambrechts @ChristianFurbo @MeloOspino I try to add the normalization again. What do you think of these values? https://github.com/metagenome-atlas/atlas/blob/879ded0562533f56384760867ee9bd701f95c466/atlas/template_config.yaml#L84-L87

**Comment by MeloOspino** [comment]
> @slambrechts @ChristianFurbo @MeloOspino I try to add the normalization again. What do you think of these values?
> 
> https://github.com/metagenome-atlas/atlas/blob/879ded0562533f56384760867ee9bd701f95c466/atlas/template_config.yaml#L84-L87

Hi @SilasK . Thanks!. I used the normalization, and it works for my MDA amplified libraries. (Hopefully, the paper will be published soon.) I applied a lower threshold in the normalization_target_depth, but I guess everyone can modify it.
On the other hand, I could not subscribe to the ATLAS seminar, but my husband did. So if it is ok, Can I do the seminar with him.? Thank you for all the work you do on ATLAS. It is a fantastic pipeline.

**Comment by SilasK** [comment]
Thank you for your feedback on the normalization. If the publication gets output it on the #421 
For the course. Send me a mail and you can participate as an independent participant. Looking forward to seeing you.

**Comment by SilasK** [comment]
@MeloOspino BBnorm for me takes very long and uses a lot of memory even for a very small dataset. Maybe I should decrease the kmer size.. Do you have any other suggestions.

**Comment by MeloOspino** [comment]
> Thank you for your feedback on the normalization. If the publication gets output it on the #421
> For the course. Send me a mail and you can participate as an independent participant. Looking forward to seeing you.

Yeah, once it is publish (finger cross) I will add it. And, Thank you for letting me participate in the seminar. My mail is melody.cabrera.ospino@gmail.com.

**Comment by MeloOspino** [comment]
> @MeloOspino BBnorm for me takes very long and uses a lot of memory even for a very small dataset. Maybe I should decrease the kmer size.. Do you have any other suggestions.

From the BBnorm page: `"Normalization is often useful if you have too much data (for example, 600x average coverage when you only want 100x) or uneven coverage (amplified single-cell, RNA-seq, viruses, metagenomes, etc). It is not useful if you have smooth coverage and approximately the right amount of data, or too little data. BBNorm cannot inflate low coverage (bring 15x coverage up to 100x), only reduce it."`
In my case, I use multiple displacement amplification in samples with low abundance DNA biomass, resulting in libraries with highly uneven coverage, from 10x to >10000x. I use a normalization_target_depth to 40x as a threshold to assembler in spades.  Without the normalization, SPADES was constantly crashing. I also use MEGAHIT without normalization to compare. Overall normalization + SPADES performed slightly better than megahit.  

Maybe the normalization_target_depth set to 1000 is too high. I am not that proficience, but my experience will help you.

**Pull request merged**
