### PR TITLE
predict genes in parallel

### PR DESCRIPTION
**Pull request by SilasK**
#239

### CODE REVIEW

**Comment by SilasK** [comment]
Another option would be to put predict genes directly as snakemake rule, this would add some overhead to snakemake to calculate the dag for all your MAGs but would allow to simplify the naming of log files and re-runing.

**Comment by jmtsuji** [comment]
N.B., this PR also addresses spelling issue in #239

**Comment by jmtsuji** [comment]
@SilasK I was thinking about overhead for snakemake; this is why I left parallel gene prediction up to the script, not snakemake. Gene prediction does not take that long (~1 min. per genome on 1 thread), so I do not think it is large enough of a bottleneck at this point to necessarily require distribution across a cluster. Thoughts?

**Comment by jmtsuji** [comment]
@SilasK Logging is now improved. Logs for individual prodigal runs are placed into a tmp folder with a UUID to prevent file collisions, and each log contains the name of the corresponding MAG. The tmp folder is removed after the log entries are concatenated.

The new script and rule works in ATLAS when I test locally.

Okay to merge?

**Comment by jmtsuji** [comment]
Agreed -- cat in Python makes sense

**Pull request merged**
